"use client";

import { useEffect, useState } from "react";
import { createMemberProfile, deleteMemberProfile, getMembers, updateMemberProfile } from "@/lib/api/members";
import type { MemberProfile } from "@/lib/api/types";
import { StudioShell } from "@/components/studio/StudioShell";
import { ErrorState, LoadingSkeleton, TacticalCard } from "@/components/ui/states";
import { useSession } from "@/lib/session/use-session";

export default function StudioProfilePage() {
  const { user } = useSession();
  const [profile, setProfile] = useState<MemberProfile | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ display_name: "", designation: "", year: "First Year", bio: "", pfp_url: "", email: "", show_email: false, linkedin_url: "", personal_site: "" });
  const load = async () => { setLoading(true); setError(null); try { const data = await getMembers(); const own = (data.members || []).find((member) => member.user_id === user?.user_id) || null; setProfile(own); if (own) setForm({ display_name: own.display_name || "", designation: own.designation || "", year: own.year || "First Year", bio: own.bio || "", pfp_url: own.pfp_url || "", email: own.email || "", show_email: !!own.show_email, linkedin_url: own.linkedin_url || "", personal_site: own.personal_site || "" }); else setForm((current) => ({ ...current, display_name: user?.display_name || "" })); } catch (err) { setError(err instanceof Error ? err.message : "Could not load profile"); } finally { setLoading(false); } };
  useEffect(() => { if (user) void load(); }, [user]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { if (profile) await updateMemberProfile(profile._id, form); else await createMemberProfile(form); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Could not save profile"); } finally { setSaving(false); } };
  return <StudioShell title="Society Card" intro="Create or maintain your public member profile.">{loading && <LoadingSkeleton />}{error && <ErrorState message={error} onRetry={load} />}{!loading && <TacticalCard><form onSubmit={submit} className="grid gap-4"><input required className="border border-gold/20 bg-ink p-3 text-white" placeholder="Display name" value={form.display_name} onChange={(e) => setForm({ ...form, display_name: e.target.value })} /><input className="border border-gold/20 bg-ink p-3 text-white" placeholder="Designation" value={form.designation} onChange={(e) => setForm({ ...form, designation: e.target.value })} /><select className="border border-gold/20 bg-ink p-3 text-white" value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value })}>{["Core Committee","Third Year","Second Year","First Year","Alumni"].map((item) => <option key={item}>{item}</option>)}</select><textarea maxLength={300} className="min-h-28 border border-gold/20 bg-ink p-3 text-white" placeholder="Bio (300 chars)" value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /><input className="border border-gold/20 bg-ink p-3 text-white" placeholder="Profile photo URL" value={form.pfp_url} onChange={(e) => setForm({ ...form, pfp_url: e.target.value })} /><input className="border border-gold/20 bg-ink p-3 text-white" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><label className="flex gap-3 text-white/70"><input type="checkbox" checked={form.show_email} onChange={(e) => setForm({ ...form, show_email: e.target.checked })} /> Show email publicly</label><input className="border border-gold/20 bg-ink p-3 text-white" placeholder="LinkedIn URL" value={form.linkedin_url} onChange={(e) => setForm({ ...form, linkedin_url: e.target.value })} /><input className="border border-gold/20 bg-ink p-3 text-white" placeholder="Personal site" value={form.personal_site} onChange={(e) => setForm({ ...form, personal_site: e.target.value })} /><button disabled={saving} className="bg-gold px-5 py-3 text-xs font-semibold uppercase tracking-[0.2em] text-navy disabled:opacity-50">{saving ? "Saving..." : profile ? "Save Profile" : "Create Profile"}</button>{profile && <button type="button" onClick={() => confirm("Delete your profile?") && void deleteMemberProfile(profile._id).then(load)} className="border border-crimson/50 px-5 py-3 text-xs uppercase tracking-[0.2em] text-red-200">Delete Profile</button>}</form></TacticalCard>}</StudioShell>;
}
